name: deploy-auth-prod
on:
    push:
        branches:
            - main
        paths:
            - "packages/auth/**"
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Deploying auth prod"
