name: deploy-grading-dev
on:
    push:
        branches:
            - dev
        paths:
            - "packages/grading/**"
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Deploying grading dev"
