name: deploy-manifest-prod

on:
    push:
        branches:
            - main
        paths:
            - "packages/infra/**"
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Deploying manifest prod"
