name: deploy-courses-dev
on:
    push:
        branches:
            - dev
        paths:
            - "packages/courses/**"
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Deploying courses dev"
