name: deploy-manifest-dev

on:
    push:
        branches:
            - dev
        paths:
            - "packages/infra/**"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Deploying manifest dev"
