name: deploy-manifest-dev

on:
    push:
        branches:
            - dev
        paths:
            - "packages/infra/**"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Azure Login
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}

            - name: Gets K8s context
              uses: azure/aks-set-context@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}
                  resource-group: ${{ secrets.RESOURCE_GROUP }}
                  cluster-name: ${{ secrets.CLUSTER_NAME_DEV }}
              id: login

            - run: kubectl apply -f packages/infra/k8s && kubectl apply -f packages/infra/k8s-dev
