name: deploy-grading-prod

on:
    push:
        branches:
            - main
        paths:
            - "packages/grading/**"
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Deploying grading prod"
