name: deploy-courses-prod
on:
    push:
        branches:
            - main
        paths:
            - "packages/courses/**"
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Deploying courses prod"
