name: deploy-auth-dev
on:
    push:
        branches:
            - dev
        paths:
            - "packages/auth/**"
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Deploying auth dev"
