name: deploy-swagger-dev
on:
    push:
        branches:
            - dev
        paths:
            - "packages/swagger/**"
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Deploying swagger dev"
