name: deploy-swagger-prod
on:
    push:
        branches:
            - main
        paths:
            - "packages/swagger/**"
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Deploying swagger prod"
